# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RonsBotApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ronscbreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6a2579a2850845c4a097783b2ef8de94 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f23f908573b64c70a211d56816e863cb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ronscbreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6a2579a2850845c4a097783b2ef8de94 }}/app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RonsBotApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3dbdfd351d904ced8a76fa6db04d1cce }}
        images: 'ronscbreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6a2579a2850845c4a097783b2ef8de94 }}/app:${{ github.sha }}'