# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RonsBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ronsbotreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f74fff2314e9431e92f2a445a0ed9c7f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_487bbd52e67e4d43af94e6680c8107ca }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ronsbotreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f74fff2314e9431e92f2a445a0ed9c7f }}/chatbot-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RonsBot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4ee314d1dc9c4e53a680d51213b11eef }}
        images: 'ronsbotreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f74fff2314e9431e92f2a445a0ed9c7f }}/chatbot-app:${{ github.sha }}'